# 
# Automagically generated file.
# generated by gensrc/gen_pkgmake.k
# 

CC = gcc
CFLAGS = -O2 -Wall -fmessage-length=0 -fPIC 
LDLIBS = -lkonoha -lssl 
target = linux_32
pkgname = openssl

library = "$(pkgname)_$(target).so"

objs = sha1.o 

.PHONY: all
all: $(library)

$(library): $(objs)
	$(CC) -shared -o $@ $^ $(LDLIBS)

sha1.o : ./src/sha1.c
	$(CC) $(CFLAGS) -o $@ -c $^

.PHONY: clean
clean:
	$(RM) -rf $(objs) $(library)

